[package]
authors = ["Cass Fridkin <cass@cloudflare.com>"]
edition = "2018"
name    = "ratmap"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amf          = "0.3.1"
const-random = "0.1.13"
deku         = "0.11.0"
